name: image

on:
  push:
    tags:
      - '*'

env:
  KUBERNETES_VERSION: 1.34.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.3.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0

      - name: Login to GCR
        uses: docker/login-action@v3.3.0
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.PUBLIC_GCR_JSON_KEY }}

      - name: Extract version from tag
        id: version
        run: |
          # Remove 'v' prefix if present
          VERSION=${GITHUB_REF#refs/tags/v}
          VERSION=${VERSION#refs/tags/}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6.13.0
        with:
          build-args: |
            KUBERNETES_VERSION=${{ env.KUBERNETES_VERSION }}
          context: .
          push: true
          tags: |
            eu.gcr.io/swade1987/kubernetes-toolkit:latest
            eu.gcr.io/swade1987/kubernetes-toolkit:${{ env.VERSION }}
