name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.PUBLIC_GCR_JSON_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            KUBERNETES_VERSION=1.21.8
          context: .
          push: true
          tags: eu.gcr.io/swade1987/kubernetes-toolkit:1.21.8
