name: ci

on:
  push:
    branches:
      - 'master'

env:
  KUBERNETES_VERSION: 1.32.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GCR
        uses: docker/login-action@v3
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.PUBLIC_GCR_JSON_KEY }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            KUBERNETES_VERSION=${{ env.KUBERNETES_VERSION }}
          context: .
          push: true
          tags: eu.gcr.io/swade1987/kubernetes-toolkit:${{ env.KUBERNETES_VERSION }}
